### PR TITLE
Major Internal Update

### PR DESCRIPTION
**Pull request by Lbniese**
This pull consists of 39 commits of different size.
The logging system has been updated a changed a lot.
A lot of pathing and spell fixes have been applied.
Questing and dungeon scripts have been updated etc.

### CODE REVIEW

**Comment by kigiri** [comment]
Hey man,  please format your code to respect the way TrinityCore is indented (4 spaces) and avoid mixing cosmetic changes with features.

**Comment by Lbniese** [comment]
@kigiri would you mind showing me a few examples of where you are not satisfied with the formatting?
My formatting comes from Visual Studio, but I will of course update it to match what you want.

Also can you elaborate on the "mixing cosmetic changes with features" thingy?

**Comment by kigiri** [comment]
@Lbniese  you should configure visual studio to use 4 space as indent style and tell him not to commit white space changes then.
Also please carefull with removing the last return at the end of a file, it's required by some compilers.
in this commit for example : https://github.com/Lbniese/ngen-dev/commit/e367839c54789cece089ce7a2a1a6fb6c1ce5d9d
the 2 last files only have white space changes and you removed last end of file, while in reality no changes were made on them and so they shouldn't be commited.
Or in an other commit that fix the indent if the indentation was wrong, but it wasn't.

**Comment by Lbniese** [comment]
@kigiri I will update the indent style now.
I do not see where you have removed the last return at the end of a file.

**Comment by kigiri** [comment]
@Lbniese Great, it's shown here with this icon : image

**Comment by Lbniese** [comment]
@kigiri do you know if there is any smart ways to add it back besides reverting all the code?

**Comment by kigiri** [comment]
i'm gonna try merging ignoring white spaces with --ignore-all-space

**Comment by kigiri** [comment]
It turns out it's ignoring white space that could conflict the merge but merging with the wrong white spaces in the end :/
I guess we have to remove them manualy.

**Comment by Lbniese** [comment]
Will do it when I get some more time.

**Pull request closed without merging**
